name: mLevels
version: '1.2'
main: com.skypvp.mlevels.Main
author: Moody - _Yasta
description: "A Configurable Gear Leveling System Plugin."
softdepend: [PlaceholderAPI, PlayerKits2]

commands:
  mlevels:
    description: "mLevels admin commands"
    usage: /mlevels <reload|set|add|remove|check|reset>
    aliases: [mlvl, levelup]
  level:
    description: "Shows your current level"
    usage: /level [player]

permissions:
  mlevels.admin:
    description: "Permission to manage the plugin (reload/set/add/remove/reset)"
    default: op
